# Generated by Django 4.2 on 2024-07-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_citydata_weatherdata_delete_cityforcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='citydata',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
