# Generated by Django 4.2 on 2024-07-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_citydata_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
