# Generated by Django 4.2 on 2024-07-19 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_weatherdata_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citydata',
            name='slug',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='weather.citydata'),
        ),
    ]
